### ISSUE TITLE
大佬，部署成功之后分配的域名和argo域名都打不开呀

### ISSUE THREAD

**Issue by AdriangnoH** [fscarmen2/X-for-Botshard-ARM#1]

**Comment by fscarmen2** [comment]
我选的是德国区，这个区是arm架构，可能别的区是amd架构的导致使用不了，只要把几个软件换成for amd64的就行了，具体可以参考：https://github.com/fscarmen2/X-for-stozu

**Comment by AdriangnoH** [comment]
我也选了德国区，部署后显示已经在保活了，但是分配的域名挂不挂梯子都访问不了，argo域名也打不开显示error1033，按理说打开argo域名应该是bad request，不知道问题出在哪了

**Comment by AdriangnoH** [comment]
我弄好了，argo域名和token填反了，看了list才发现，被自己蠢哭
